# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo-dev
    image: mongo:5.0.4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 2717:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_ROOT_DATABASE=vaccination


